apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo-helm.fullname" . }}-odoo-app-credentials
  labels:
  {{- include "odoo-helm.labels" . | nindent 4 }}
data:
  admin-password: {{ required "odooAppCredentials.adminPassword is required" .Values.odooAppCredentials.adminPassword
    | b64enc | quote }}
  admin-user: {{ required "odooAppCredentials.adminUser is required" .Values.odooAppCredentials.adminUser
    | b64enc | quote }}
  master-password: {{ required "odooAppCredentials.masterPassword is required" .Values.odooAppCredentials.masterPassword
    | b64enc | quote }}
type: Opaque
